### ISSUE TITLE
Misspelled word "dictionnary"

### ISSUE THREAD

**Issue by DiGro** [OmegaT-L10N/nl#1]
In doc_src/Omegat4_ProjectFolder.xml the word "dictionnary" is misspelled.
dictionnary<segment 4010>

It should have one "n", not two

**Comment by kosivantsov** [comment]
The typo is now corrected upstream. Please update the corresponding segment in the translation.

**Comment by DiGro** [comment]
Done.
Thanks

__________
DiGro 

    Op dinsdag 28 mei 2019 13:31:39 CEST schreef Kos Ivantsov <notifications@github.com>:  
 
 
Closed #1.
